pipeline {
  
  agent any
  
  stages{
    
    stage("build"){
      steps{
        echo 'building the application'
        echo 'making a change at 2:03 am'
      }
    }

    stage("test"){
      steps{
        echo 'testing the application'
      }
    }

    stage("deploy"){
      steps{
        echo 'deploying the application'
      }
    }
  
  }
}
